name: shopmate
description: Shopmate is a revolutionary app designed to enhance the shopping experience for all.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+2

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
      sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  http: ^1.1.0
  provider: ^6.0.5
  intl: ^0.18.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.2



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo/appLogo.png"
  min_sdk_android: 16




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  generate: true

  uses-material-design: true


  assets:
    - assets/groceries_list_data/vegetable.json
    - assets/groceries_list_data/fruit.json
    - assets/groceries_list_data/meat.json
    - assets/groceries_list_data/seafood.json
    - assets/groceries_list_data/dairy.json
    - assets/groceries_list_data/ingredient.json
    - assets/app_logo/appLogo.png
    - assets/vegetables/cabbage.png
    - assets/vegetables/broccoli.png
    - assets/vegetables/butternut_pumpkins.png
    - assets/vegetables/carrot.png
    - assets/vegetables/chili.png
    - assets/vegetables/mushroom.png
    - assets/vegetables/onion.png
    - assets/vegetables/radish.png
    - assets/vegetables/tomato.png
    - assets/vegetables/potato.png
    - assets/fruits/apple.png
    - assets/fruits/avocado.png
    - assets/fruits/banana.png
    - assets/fruits/grape.png
    - assets/fruits/guava.png
    - assets/fruits/mango.png
    - assets/fruits/orange.png
    - assets/fruits/pineapple.png
    - assets/fruits/pomegranate.png
    - assets/fruits/strawberry.png
    - assets/meats/beef_1.png
    - assets/meats/beef_2.png
    - assets/meats/chicken_breast.png
    - assets/meats/chicken_full.png
    - assets/meats/pork_1.png
    - assets/meats/pork_2.png
    - assets/seafoods/fish_1.png
    - assets/seafoods/shrimp_1.png
    - assets/dairies/cheese.png
    - assets/dairies/egg.png
    - assets/dairies/milk_packet.png
    - assets/dairies/yogurt.png
    - assets/ingredients/chili.png
    - assets/ingredients/cumin.png
    - assets/ingredients/pepper.png
    - assets/ingredients/salt.png

